package gedit.model;
public interface jpgsym {
    int
      TK_DROPSYMBOLS_KEY = 33,
      TK_DROPACTIONS_KEY = 34,
      TK_DROPRULES_KEY = 35,
      TK_NOTICE_KEY = 16,
      TK_AST_KEY = 17,
      TK_GLOBALS_KEY = 18,
      TK_DEFINE_KEY = 19,
      TK_TERMINALS_KEY = 20,
      TK_KEYWORDS_KEY = 21,
      TK_EOL_KEY = 7,
      TK_EOF_KEY = 10,
      TK_ERROR_KEY = 6,
      TK_IDENTIFIER_KEY = 8,
      TK_ALIAS_KEY = 22,
      TK_EMPTY_KEY = 4,
      TK_START_KEY = 23,
      TK_TYPES_KEY = 24,
      TK_RULES_KEY = 25,
      TK_NAMES_KEY = 26,
      TK_END_KEY = 5,
      TK_HEADERS_KEY = 27,
      TK_TRAILERS_KEY = 28,
      TK_EXPORT_KEY = 29,
      TK_IMPORT_KEY = 30,
      TK_INCLUDE_KEY = 31,
      TK_RECOVER_KEY = 32,
      TK_MACRO_NAME = 2,
      TK_SYMBOL = 1,
      TK_BLOCK = 3,
      TK_EQUIVALENCE = 11,
      TK_PRIORITY_EQUIVALENCE = 13,
      TK_ARROW = 12,
      TK_PRIORITY_ARROW = 14,
      TK_OR = 9,
      TK_EOF = 15,
      TK_EOL = 36,
      TK_ERROR = 37,
      TK_COMMENT = 38,
      TK_OPTION_LINE = 39;

      String orderedTerminalSymbols[] = {
                 "",
                 "SYMBOL",
                 "MACRO_NAME",
                 "BLOCK",
                 "EMPTY_KEY",
                 "END_KEY",
                 "ERROR_KEY",
                 "EOL_KEY",
                 "IDENTIFIER_KEY",
                 "OR",
                 "EOF_KEY",
                 "EQUIVALENCE",
                 "ARROW",
                 "PRIORITY_EQUIVALENCE",
                 "PRIORITY_ARROW",
                 "EOF",
                 "NOTICE_KEY",
                 "AST_KEY",
                 "GLOBALS_KEY",
                 "DEFINE_KEY",
                 "TERMINALS_KEY",
                 "KEYWORDS_KEY",
                 "ALIAS_KEY",
                 "START_KEY",
                 "TYPES_KEY",
                 "RULES_KEY",
                 "NAMES_KEY",
                 "HEADERS_KEY",
                 "TRAILERS_KEY",
                 "EXPORT_KEY",
                 "IMPORT_KEY",
                 "INCLUDE_KEY",
                 "RECOVER_KEY",
                 "DROPSYMBOLS_KEY",
                 "DROPACTIONS_KEY",
                 "DROPRULES_KEY",
                 "EOL",
                 "ERROR",
                 "COMMENT",
                 "OPTION_LINE"
             };

    boolean isValidForParser = true;
}
